# Generated by Django 4.1.4 on 2022-12-20 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_payment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expired_payments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('penalty_fee_amount', models.FloatField(default=0.0)),
                ('payment_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.payment_user')),
            ],
            options={
                'db_table': 'expired_payments',
            },
        ),
    ]
